proxy:
    defaultHost: rest.secure-proxy.lan
    port: 9443
sessions:
    cookieDomain: .secure-proxy.lan
    cookieName: SECURE_PROXY_SESSION
    ttlSeconds: 18000
users:
    - username: sklad
      totpSecret: VGLFTEMMJYNRCC36PNS6ZCURQPLYAXRY
      allowedPaths:
        - rest.secure-proxy.lan/warehouse
        - rest.secure-proxy.lan/kitchen
    - username: выпывп
      totpSecret: 3PEANXK3QDP2MKUN3NSH7CDSTJOFKCK3
      allowedPaths:
        - docker-compose restart proxy
upstreams:
    - host: rest.secure-proxy.lan
      destination: http://host.docker.internal:8000
